fun main() {
    println("21012011049_Meha Bhatt\n")
    println("Enter student information:\n")
    print("Student Enrolment No.: ")
    val erl = readLine()?.toLong()
    print("Student Name: ")
    val name = readLine()
    print("Student Branch: ")
    val branch = readLine()
    print("Student Class: ")
    val c = readLine()
    print("Student Batch: ")
    val batch = readLine()
    print("Student College Name: ")
    val clg = readLine()
    print("Student University Name: ")
    val uni = readLine()
    print("Student Age: ")
    val age = readLine()?.toInt()
    println("\n************************")
    println("\nStudent Information:\n")
    println("Enrolment Number: $erl")
    println("Name: $name")
    println("Age: $age")
    println("Branch: $branch")
    println("Class: $c")
    println("Batch: $batch")
    println("College Name: $clg")
    println("University Name: $uni")

}